version: "3.9"
services:
  redacted-tes:
    depends_on:
      - db
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
    environment:
      - ENV=prd
      - DB_USER=postgres
      - DB_PASSWORD=postgrespw
      - DB_HOST=db.internal
      - DB_PORT=5432
      - DB_NAME=postgres
    ports:
      - "8080:80"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 512M

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    networks:
      default:
        aliases:
          - db.internal
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 1G

networks:
  default:
    external: false
    name: redacted-tes-network