"""bootstrap database

Revision ID: e00824bb465e
Revises: 
Create Date: 2024-12-05 00:18:24.396706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e00824bb465e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('historico_credito', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('renda_estimada', sa.DECIMAL(precision=17, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=17, scale=2), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('negociacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('negociacoes')
    op.drop_table('imoveis')
    op.drop_table('compradores')
    # ### end Alembic commands ###
